
### Practice Questions — Session 6 (Indexing & Slicing)
---
#### SESSION 6

In [1]:
import numpy as np

1.
Create a 1D NumPy array:
arr = [10, 20, 30, 40, 50]
Print:
- First element
- Last element using negative indexing

In [2]:
arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])

10
50


### 2.
Given array:
arr = [5, 10, 15, 20, 25, 30]
Extract elements from index 1 to 4 using slicing.

In [3]:
arr = np.array([5,10,15,20,25,30])
print(arr[1:5])

[10 15 20 25]


### 3.
Given array:
arr = [0, 2, 4, 6, 8, 10]
Extract every second element using step slicing.

In [5]:
arr = np.array([0,2,4,6,8,10])
print(arr[::2])

[0 4 8]


### 4.
Create a 2D array:
[[1, 2, 3],
[4, 5, 6],
[7, 8, 9]]
Print the element located at:
Row 2, Column 1 (using proper indexing).

In [9]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr[1,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
4


### 5.
Using the same 2D array from Question 4,
Extract the first two rows.

In [10]:
print(arr)
print(arr[0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]


### 6.
Using the same 2D array,
Extract the submatrix:
[[2, 3],
[5, 6]]

In [11]:
print(arr)
print(arr[0:2,1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]


#### 7.
Create array:
arr = [10, 20, 30, 40, 50]
Using fancy indexing, extract:
- 1st element
- 3rd element
- 5th element

### 8.
Create array:
arr = [5, 10, 15, 20, 25]
Using boolean indexing, extract elements greater than 12.

### 9.
Given array:
arr = [3, 6, 9, 12, 15]
Use np.where() to find indices where values are greater than 8.

### 10.
Create array:
arr = [1, 2, 3, 4, 5]
Reverse the array using slicing.

#### REVISION QUESTIONS (Previous Sessions — 2 Questions)
### 11. (Array Operations)
Create arrays:
a = [2, 4, 6]
b = [1, 2, 3]
Perform:
- Element-wise multiplication
- Element-wise power (a squared)

### 12. (Mathematical Functions)
Create array:
arr = [4, 9, 16, 25]
Compute:
- Square root
- Mean
- Maximum value
[Quoted text hidden]