## Numpy -3 Assignment questions 

In [2]:
import numpy as np

1. Create an array from 1 to 15.

        Split it into 5 equal parts.

In [5]:
arr = np.arange(1,16)
arr2= np.split(arr,5)
print(arr2)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12]), array([13, 14, 15])]


Q2. 

Create an array from 1 to 11.

Split it into 4 parts using array_split().

In [8]:
arr = np.arange(1,12)
arr2 = np.array_split(arr,3)
print(arr2)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11])]


Q3.

Given: arr = np.array([10, 20, 30, 40, 50])

Insert 25 at index 2.

In [9]:
arr = np.array([10,20,30,40,50])
arr2 = np.insert(arr,2,25)
print(arr2)

[10 20 25 30 40 50]


Q4.

Given: arr = np.array([[1,2], [3,4]])

Insert a new row [5,6] at index 1.

In [15]:
arr = np.array([[1,2], [3,4]])
arr2 = np.insert(arr,1,[5,6],axis=0)
print(arr2)

[[1 2]
 [5 6]
 [3 4]]


Q5.
Given: arr = np.array([5, 10, 15])
Append 20 and 25 at the end.

In [16]:
arr = np.array([5,10,15])
arr2 = np.append(arr,[20,25])
print(arr2)

[ 5 10 15 20 25]


Q6.

Given: arr = np.array([[1,2], [3,4]])
Append column [7,8] to this array.


### this was tricky need to give attention


In [24]:
arr = np.array([[1,2], [3,4]])
arr2 = np.append(arr, [[7], [8]], axis=1)
print(arr2)

[[1 2 7]
 [3 4 8]]


Q7.

Given: arr = np.array([100, 200, 300, 400, 500])
Delete: a) Element at index 3
b) First two elements

In [27]:
arr = np.array([100,200,300,400,500,600])
arr2 = np.delete(arr,3)
print(arr2)
arr3 = np.delete(arr,[0,1]) # when delte mpre than one elemnt give the list of indexes to be deleted
print(arr3)

[100 200 300 500 600]
[300 400 500 600]


Q8.

Given: arr = np.array([[1,2], [3,4], [5,6]])
Delete the second row.

In [29]:
arr = np.array([[1,2], [3,4], [5,6]])
arr2 = np.delete(arr,1,axis=0) # delete the second row
print(arr2)

[[1 2]
 [5 6]]


Q9.

Create: arr = np.array([1,2,3,4])
Create:

· view_arr using view()
. copy_arr using copy()
Modify arr[O] = 999
Print all three arrays. Explain what happened.

In [38]:
arr = np.array([1,2,3,4])
print("original array :",arr)

view_arr = arr.view()
copy_arr = arr.copy()

arr[0]=10
print("after changing the original array")
print("original array :",arr)
print("View array:- ", view_arr)
print("Copy array:- ", copy_arr)
print("after changing the original array the view array was alos changes as view shares the memory refernce with the original ,\n where copy greates a new memory refernce and copy the elemts ")


original array : [1 2 3 4]
after changing the original array
original array : [10  2  3  4]
View array:-  [10  2  3  4]
Copy array:-  [1 2 3 4]
after changing the original array the view array was alos changes as view shares the memory refernce with the original ,
 where copy greates a new memory refernce and copy the elemts 


Q10.

Create array from 1 to 6. Reshape it into 2×3 matrix. Change element at position (0,1) to 100.

In [39]:
arr = np.arange(1,7).reshape(2,3)
arr[0,1] =100
print(arr)


[[  1 100   3]
 [  4   5   6]]


Q11.

Given: arr = np.array([[1,2,3], [4,5,6]])
Apply:

· flatten()
· ravel()
Modify first element of both results. Observe difference.

In [6]:
arr = np.array([[1,2,3,4],[4,5,6,8]])
print(arr)
arr1 = arr.flatten()
arr1[3]=100
print(arr, arr1)
arr = np.array([[1,2,3,4],[4,5,6,8]])
arr2 = arr.ravel()
arr2[3] = 100
print(arr, arr2)

print("\n flastten doesn't change the first arr as it duplicated the array , where the ravel just passs the refernce and the original array also got modified by changing the new array created with ravel Method")

[[1 2 3 4]
 [4 5 6 8]]
[[1 2 3 4]
 [4 5 6 8]] [  1   2   3 100   4   5   6   8]
[[  1   2   3 100]
 [  4   5   6   8]] [  1   2   3 100   4   5   6   8]

 flastten doesn't change the first arr as it duplicated the array , where the ravel just passs the refernce and the original array also got modified by changing the new array created with ravel Method


Q12.

Create array from 1 to 12. Split into 3 equal parts. Delete last element from each part. Combine all remaining elements into a single array.

In [19]:
arr = np.arange(1,13)

arr1 = np.split(arr,3)
combine_array = []

print(arr1)
print(type(arr1))

arr2 = [split[:-1] for split in arr1]
print(arr2)

for split in arr1:
    combine_array.extend(split)

print(combine_array)
combine_array = np.array(combine_array)
print(combine_array)
print(type(combine_array))

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]
<class 'list'>
[array([1, 2, 3]), array([5, 6, 7]), array([ 9, 10, 11])]
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12)]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
<class 'numpy.ndarray'>


## 22 questions 2nd part 

1.

Create a 4×4 matrix using np.arange(1,17).

    .Extract the second row.
    . Extract the last column.
    . Compute the mean of the entire matrix.

In [13]:
mat = np.arange(1,17).reshape(4,4)
print(mat)
seco_row = mat[1]
print(seco_row)
last_column = mat[:,-1]
print(last_column)

mean_valu = np.mean(mat)
print(mean_valu)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[5 6 7 8]
[ 4  8 12 16]
8.5


2.

Create array: arr = [5, 10, 15, 20, 25, 30]

. Extract elements greater than 10 AND less than 30.

. Find their cumulative sum.

In [18]:
arr = np.array([5,10,15,20,35,30])
print(arr[(arr>10) & (arr<30)])
sum = np.cumsum(arr)
print(sum)

[15 20]
[  5  15  30  50  85 115]


3.

Generate 10 random integers between 1 and 50.

. Sort them.

. Return indices that would sort the original array.

. Find the 75th percentile.


In [23]:
arr = np.random.randint(1,50,10)
print(arr)
arr.sort()
print(arr)
print(np.percentile(arr,75))

[ 2 33 22  1 30 18 41 11 22 38]
[ 1  2 11 18 22 22 30 33 38 41]
32.25


4.

Create two 2×3 matrices.

. Concatenate them row-wise.
. Then split the result into 2 equal parts.

In [31]:
mat = np.arange(1,7).reshape(2,3)
mat1 = np.arange(7,13).reshape(2,3)
print(mat)
print(mat1)
mat3 = np.concatenate((mat,mat1) , axis =0)
print(mat3)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


5.

Create array: arr = [1, 2, 2, 3, 4, 4, 5]
· Remove duplicate values.
. Reverse the array using slicing.
. Compute standard deviation.

In [38]:
arr = np.array([1,2,2,4,5,323,554,6,66,6,2,5,3,5,2,1,1,1])
arr = np.unique(arr)
print(arr)
print(type(arr))

rev_arr = arr[::-1]
print(rev_arr)

[  1   2   3   4   5   6  66 323 554]
<class 'numpy.ndarray'>
[554 323  66   6   5   4   3   2   1]


6.

Create a 5×5 matrix using np.arange(1,26).
. Extract all elements greater than 10 and less than 20.
. Replace those values with O using boolean indexing.
. Compute total sum of modified matrix.


In [47]:
arr = np.arange(1,26).reshape(5,5)
print(arr)
print("---...")
sum_ = np.sum(arr)
arr1 = arr[(arr>10) & (arr<20)]
print(arr1)
print("---...")
print((arr>10) & (arr<20) )
print("---...")
arr[np.where((arr>10) & (arr<20))] = 0
print(arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
---...
[11 12 13 14 15 16 17 18 19]
---...
[[False False False False False]
 [False False False False False]
 [ True  True  True  True  True]
 [ True  True  True  True False]
 [False False False False False]]
---...
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 0  0  0  0  0]
 [ 0  0  0  0 20]
 [21 22 23 24 25]]


7.

Generate 1000 random numbers from normal distribution.
. Compute mean and standard deviation.
. Clip values between -1 and 1.
. Count how many values were clipped.

## good concept of clipping and count how many clipped

In [60]:
arr = np.random.randn(1000)

print(np.mean(arr))
print(np.std(arr))
count = np.clip(arr,-1,1)

differen = np.sum(count != arr)
print(differen)



-0.10691444409849821
1.0218373211618461
309


8.

Create array: arr = [10, 20, np.nan, 40, 50, np.nan]
. Compute mean ignoring NaN.
. Replace NaN values with O.
. Compute new mean.

In [80]:
arr = np.array([10,20,np.nan,40,50,np.nan])
means = np.mean(arr)
print(means)
means = np.nanmean(arr)
print(means)

print(np.isnan(arr))
print(arr)

arr[np.isnan(arr)] = (np.nanstd(arr) + np.nanmean(arr))/2
print(arr)
print(np.mean(arr))

nan
30.0
[False False  True False False  True]
[10. 20. nan 40. 50. nan]
[10.         20.         22.90569415 40.         50.         22.90569415]
27.63523138347365


9.

Create two matrices: A (3×3) using np.arange() B (3×3) random integers between 1 and 10.
. Perform element-wise multiplication.
. Compute 90th percentile of result.

In [95]:
a = np.arange(1,10).reshape(3,3)
b = np.random.randint(1,10,9).reshape(3,3)
print(a,"\n-----\n",b)

# elemt wise muiltipcation is easy u=just a*b
c = a*b
print("---")
print(c)

print(np.percentile(c,90))


[[1 2 3]
 [4 5 6]
 [7 8 9]] 
-----
 [[1 6 3]
 [3 5 5]
 [9 9 6]]
---
[[ 1 12  9]
 [12 25 30]
 [63 72 54]]
64.8


10.

Create array: arr = np.arange(1,21)
. Reshape into 4×5 matrix.
. Extract elements divisible by both 2 and 3.
. Insert value 999 at index 2.
. Delete last element.
. Verify whether all remaining values are positive.

In [117]:
del sum

In [129]:
arr = np.arange(1,21).reshape(4,5)
print(arr)
print(arr[(arr%2==0) & (arr%3==0)])

flastten_array = arr.flatten()
print(flastten_array)

flastten_array = np.insert(flastten_array, 2,999)
print(flastten_array)

flastten_array = np.delete(flastten_array, -1)
print(flastten_array)

flastten_array = flastten_array.reshape(np.shape(arr))
print(flastten_array)

sum1 = np.sum(flastten_array < 0 ) 
print(sum1)
if sum1 >0:
    print("there is a negative value ")
else:
    print("there is no negative value all positive")






[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 6 12 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  1   2 999   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20]
[  1   2 999   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[[  1   2 999   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]
0
there is no negative value all positive
