# Numpy ClassAssignment-1

### NumPy Practice Exercise Set

This exercise set is based on:

1. Array creation methods
2. Random arrays
3. Array attributes
4. Reshaping methods
5. Transpose operations

In [3]:
import numpy as np

## Section -A - Easy Level

1. Create a NumPy array using np.array() with elements [5, 10, 15, 20].
2. Create an array from O to 18 with step size 3 using np.arange().
3. Create 6 evenly spaced numbers between 1 and 3 using np.linspace().
4. Create a 2×4 zero matrix.

5. Create a 3×3 matrix filled with ones.

6. Generate a 2×2 matrix of random numbers from uniform distribution.
7. Create an identity matrix of size 4.

8. Find the shape, size, and number of dimensions of the following array:
np.array([[1,2,3],[4,5,6]])

1. Create a NumPy array using np.array() with elements [5, 10, 15, 20].

In [2]:
arr = np.array([5,10,15,20])
print(arr)

[ 5 10 15 20]


2. Create an array from O to 18 with step size 3 using np.arange().

In [5]:
arr = np.arange(0,18,3)
print(arr)

[ 0  3  6  9 12 15]


3. Create 6 evenly spaced numbers between 1 and 3 using np.linspace().

In [7]:
arr = np.linspace(1,3,6)
print(arr)

[1.  1.4 1.8 2.2 2.6 3. ]


4. Create a 2×4 zero matrix.

In [8]:
arr = np.zeros((2,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


5. Create a 3×3 matrix filled with ones.

In [10]:
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


6. Generate a 2×2 matrix of random numbers from uniform distribution.

In [12]:
arr = np.random.rand(2,2)
print(arr)
np.random.uniform(10, 20, (2,2))

[[0.15329813 0.21355691]
 [0.0277004  0.37260314]]


array([[18.36317535, 15.89600661],
       [13.3571963 , 15.92087236]])

7. Create an identity matrix of size 4.

In [14]:
arr = np.identity(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


8. Find the shape, size, and number of dimensions of the following array:
np.array([[1,2,3],[4,5,6]])

In [18]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.shape)
print(arr.size)
print(arr.ndim)

(2, 3)
6
2


# Section B - Medium Level Questions

9. Create an array from 1 to 12 and reshape it into a 3x4 matrix.
10. Create a 4×4 matrix using np.arange() and transpose it.
11. Generate 5 linespace spaced numbers between 10 and 30.

12. Create a random integer matrix of shape 3x3 with values between 10 and 50.

13. Create a 2×5 matrix using np.random.randn() and compute:
. Total memory consumed (nbytes)
. Size of one element (itemsize)

14. Create an array of numbers from 1 to 9 and:

    · Flatten it using ravel()
    · Flatten it using flatten()
    . Explain the difference

15. Create an empty 3×7 matrix and Transpose.


9. Create an array from 1 to 12 and reshape it into a 3x4 matrix.

In [24]:
arr = np.arange(1,13,1)
print(arr)
arr = arr.reshape(3,4)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


10. Create a 4×4 matrix using np.arange() and transpose it.

In [27]:
arr = np.arange(1,17,1).reshape(4,4)
print(arr)
arr_t = arr.T
print(arr_t)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


11. Generate 5 linespace spaced numbers between 10 and 30.

In [29]:
arr = np.linspace(10,30,5)
print(arr)

[10. 15. 20. 25. 30.]


12. Create a random integer matrix of shape 3x3 with values between 10 and 50.

In [31]:
arr = np.linspace(10,50,9).reshape(3,3)
print(arr)

[[10. 15. 20.]
 [25. 30. 35.]
 [40. 45. 50.]]


13. Create a 2×5 matrix using np.random.randn() and compute:
    1. Total memory consumed (nbytes)
    2. Size of one element (itemsize)

In [39]:
np.random.seed(42)

arr = np.random.randn(10).reshape(2,5)
print(arr)

print("Total Memrory Used- " , arr.nbytes)
print("Size of each element:- ", arr.itemsize)



[[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]
 [-0.23413696  1.57921282  0.76743473 -0.46947439  0.54256004]]
Total Memrory Used-  80
Size of each element:-  8


14. Create an 3x3 array of numbers from 1 to 9 and:

    · Flatten it using ravel()
    · Flatten it using flatten()
    . Explain the difference

In [49]:
arr = np.arange(1,10).reshape(3,3)
print(arr)

print("--Ravel--")
arr_ravel = arr.ravel()
arr_ravel[0] =100
print(arr)
print(arr_ravel)

print("--flatten--")
arr = np.arange(1,10).reshape(3,3)
arr_flatten = arr.flatten()
arr_flatten[0] = 200
print(arr)
print(arr_flatten)


print("\n\n from the Output we can see that the ravel has changed the original array where as the flatten has not changed the original array")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--Ravel--
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]
[100   2   3   4   5   6   7   8   9]
--flatten--
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[200   2   3   4   5   6   7   8   9]


 from the Output we can see that the ravel has changed the original array where as the flatten has not changed the original array


15. Create an empty 3×7 matrix and Transpose.

In [51]:
arr = np.empty((3,7))
print(arr)
arr_trans = arr.T
print(arr_trans)

[[6.95272863e-310 6.95272863e-310 1.52261400e-311 6.23053614e-307
  1.52261400e-311 9.34609789e-307 1.52261400e-311]
 [9.34600962e-307 0.00000000e+000 1.52261400e-311 1.52261400e-311
  1.52261400e-311 0.00000000e+000 6.04736351e-321]
 [7.09478267e-321 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000 2.10081501e-312]]
[[6.95272863e-310 9.34600962e-307 7.09478267e-321]
 [6.95272863e-310 0.00000000e+000 0.00000000e+000]
 [1.52261400e-311 1.52261400e-311 0.00000000e+000]
 [6.23053614e-307 1.52261400e-311 0.00000000e+000]
 [1.52261400e-311 1.52261400e-311 0.00000000e+000]
 [9.34609789e-307 0.00000000e+000 0.00000000e+000]
 [1.52261400e-311 6.04736351e-321 2.10081501e-312]]
