In [1]:
import numpy as np

1. Create an array from 1 to 15.

        Split it into 5 equal parts.

In [5]:
arr = np.arange(1,16)
arr2= np.split(arr,5)
print(arr2)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12]), array([13, 14, 15])]


Q2. 

Create an array from 1 to 11.

Split it into 4 parts using array_split().

In [8]:
arr = np.arange(1,12)
arr2 = np.array_split(arr,3)
print(arr2)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11])]


Q3.

Given: arr = np.array([10, 20, 30, 40, 50])

Insert 25 at index 2.

In [9]:
arr = np.array([10,20,30,40,50])
arr2 = np.insert(arr,2,25)
print(arr2)

[10 20 25 30 40 50]


Q4.

Given: arr = np.array([[1,2], [3,4]])

Insert a new row [5,6] at index 1.

In [15]:
arr = np.array([[1,2], [3,4]])
arr2 = np.insert(arr,1,[5,6],axis=0)
print(arr2)

[[1 2]
 [5 6]
 [3 4]]


Q5.
Given: arr = np.array([5, 10, 15])
Append 20 and 25 at the end.

In [16]:
arr = np.array([5,10,15])
arr2 = np.append(arr,[20,25])
print(arr2)

[ 5 10 15 20 25]


Q6.

Given: arr = np.array([[1,2], [3,4]])
Append column [7,8] to this array.


### this was tricky need to give attention


In [24]:
arr = np.array([[1,2], [3,4]])
arr2 = np.append(arr, [[7], [8]], axis=1)
print(arr2)

[[1 2 7]
 [3 4 8]]


Q7.

Given: arr = np.array([100, 200, 300, 400, 500])
Delete: a) Element at index 3
b) First two elements

In [27]:
arr = np.array([100,200,300,400,500,600])
arr2 = np.delete(arr,3)
print(arr2)
arr3 = np.delete(arr,[0,1]) # when delte mpre than one elemnt give the list of indexes to be deleted
print(arr3)

[100 200 300 500 600]
[300 400 500 600]


Q8.

Given: arr = np.array([[1,2], [3,4], [5,6]])
Delete the second row.

In [29]:
arr = np.array([[1,2], [3,4], [5,6]])
arr2 = np.delete(arr,1,axis=0) # delete the second row
print(arr2)

[[1 2]
 [5 6]]


Q9.

Create: arr = np.array([1,2,3,4])
Create:

· view_arr using view()
. copy_arr using copy()
Modify arr[O] = 999
Print all three arrays. Explain what happened.

In [38]:
arr = np.array([1,2,3,4])
print("original array :",arr)

view_arr = arr.view()
copy_arr = arr.copy()

arr[0]=10
print("after changing the original array")
print("original array :",arr)
print("View array:- ", view_arr)
print("Copy array:- ", copy_arr)
print("after changing the original array the view array was alos changes as view shares the memory refernce with the original ,\n where copy greates a new memory refernce and copy the elemts ")


original array : [1 2 3 4]
after changing the original array
original array : [10  2  3  4]
View array:-  [10  2  3  4]
Copy array:-  [1 2 3 4]
after changing the original array the view array was alos changes as view shares the memory refernce with the original ,
 where copy greates a new memory refernce and copy the elemts 


Q10.

Create array from 1 to 6. Reshape it into 2×3 matrix. Change element at position (0,1) to 100.

In [39]:
arr = np.arange(1,7).reshape(2,3)
arr[0,1] =100
print(arr)


[[  1 100   3]
 [  4   5   6]]


Q11.

Given: arr = np.array([[1,2,3], [4,5,6]])
Apply:

· flatten()
· ravel()
Modify first element of both results. Observe difference.

In [6]:
arr = np.array([[1,2,3,4],[4,5,6,8]])
print(arr)
arr1 = arr.flatten()
arr1[3]=100
print(arr, arr1)
arr = np.array([[1,2,3,4],[4,5,6,8]])
arr2 = arr.ravel()
arr2[3] = 100
print(arr, arr2)

print("\n flastten doesn't change the first arr as it duplicated the array , where the ravel just passs the refernce and the original array also got modified by changing the new array created with ravel Method")

[[1 2 3 4]
 [4 5 6 8]]
[[1 2 3 4]
 [4 5 6 8]] [  1   2   3 100   4   5   6   8]
[[  1   2   3 100]
 [  4   5   6   8]] [  1   2   3 100   4   5   6   8]

 flastten doesn't change the first arr as it duplicated the array , where the ravel just passs the refernce and the original array also got modified by changing the new array created with ravel Method


Q12.

Create array from 1 to 12. Split into 3 equal parts. Delete last element from each part. Combine all remaining elements into a single array.

In [19]:
arr = np.arange(1,13)

arr1 = np.split(arr,3)
combine_array = []

print(arr1)
print(type(arr1))

arr2 = [split[:-1] for split in arr1]
print(arr2)

for split in arr1:
    combine_array.extend(split)

print(combine_array)
combine_array = np.array(combine_array)
print(combine_array)
print(type(combine_array))

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]
<class 'list'>
[array([1, 2, 3]), array([5, 6, 7]), array([ 9, 10, 11])]
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12)]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
<class 'numpy.ndarray'>
