# Numpy Class assignment practice questions 


In [1]:
import numpy as np 

 ## EASY LEVEL


1. Create two arrays: a = [5, 10, 15] b = [1, 2, 3} Perform element-wise addition and multiplication.

In [2]:
array_a = np.array([5, 10,15])
array_b= np.array([1,2,3])
print(array_a + array_b)
print(array_a * array_b)



[ 6 12 18]
[ 5 20 45]


2. Given array: arr = [4, 8, 12, 16] Extract elements greater than 10.

In [3]:
item1 = np.array([4,8,12,16])
item2 = item1[item1 >10]
print(item2)

[12 16]


3. Create a 2×3 array of ones and add 5 to every element using broadcasting.

In [6]:
item1 = np.ones((2,3)) 
item2 = 5 + item1 
print(item2)

[[6. 6. 6.]
 [6. 6. 6.]]


4. Given array: arr = [10, 20, 30, 40] Compute:

    o Mean
    o Sum
    o Maximum

In [9]:
arr = np.array([10,20,30,40,50])
print(np.mean(arr))
print(np.median(arr))
print(np.max(arr))

30.0
30.0
50


5. Convert 45 degrees into radians and compute its sine value.

In [10]:
degree = 45 
radian = np.radians(degree)
sine = np.sin(radian)
print(radian,sine)

0.7853981633974483 0.7071067811865476


### MEDIUM LEVEL


6. Create two arrays: a = [2, 4, 6, 8] b = [1, 2, 3, 4] Perform floor division and modulus operations.

In [13]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([2,4,6,8])

floor_division = arr2//arr1
print(floor_division)

modulus = arr2%arr1
print(modulus)

[2 2 2 2]
[0 0 0 0]


7. Generate a 3×3 random integer matrix between 1 and 20. Find its standard deviation and variance.

In [18]:
arr1 = np.random.randint(1,20,(3,3))
print(arr1)

standard_deviation = np.std(arr1)
variance = np.var(arr1)

print(f"Standard Deviation is :- {standard_deviation} \nvariance is :- {variance}")

[[ 3 15 16]
 [ 8  5  8]
 [18 12  2]]
Standard Deviation is :- 5.517648452415616 
variance is :- 30.444444444444443


8. Create an array from 1 to 9 and reshape it into 3×3. Compute cumulative sum (cumsum).

In [19]:
arr1 = np.arange(1,10).reshape(3,3)
print(arr1)
cumsum = np.cumsum(arr1, axis=0)
print(cumsum)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


9. Create array: arr = [-3, -1, 0, 1, 3] Apply:

    o Square
    · Square root (only valid values)

In [21]:
arr1 = np.array([-3,-1,0,1,3])
square = np.square(arr1)
sqroot = np.sqrt(arr1[arr1>=0])
print(square, sqroot)

[9 1 0 1 9] [0.         1.         1.73205081]


10. Using logical operations: Given array: arr = [5, 10, 15, 20, 25] Extract values between 10 and 20 inclusive.

In [23]:
arr1 = np.array([5,10,15,20,25])
arr2 = arr1[(arr1>=10) & (arr1<=20)]
print(arr2)

[10 15 20]


### HARD LEVEL

11. Create a 3×4 matrix using np.arange(). Add a 1D array [10, 20, 30, 40] using broadcasting.

In [28]:
arr1 = np.arange(1,13).reshape(3,4)
print(arr1)
print(arr1 + np.array([10,20,30,40]))
# if column wize then change the broadcasting array shape using reshape 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]


12. Generate 1000 random numbers from normal distribution. Compute:

    o Mean
    o Standard deviation
    o 95th percentile


In [31]:
r_number = np.random.rand(1000)

print(f"The Mean is :- {np.mean(r_number)} \nThe Standard Deviation is :- {np.std(r_number)} \nThe 95th percentile is :- {(np.percentile(r_number,95))}")

The Mean is :- 0.49255580220898626 
The Standard Deviation is :- 0.28385133471182294 
The 95th percentile is :- 0.9475782260765435


13. Create two matrices: A (2×3) and B (3×2). Transpose A and verify its shape.

In [36]:
matrix_a = np.random.rand(2,3) 
matrix_b = np.random.rand(3,2)
a_t = matrix_a.transpose()
np.shape(a_t)==np.shape(matrix_b)

True

14. Create array: arr = [1, 2, 3, 4] Compute:

    o Exponential of each element
    o Natural log
    o Log hace 10

In [34]:
arr1 = np.array([1,2,3,4,])

exp = np.exp(arr1)
print(exp)
naturallog = np.log(arr1)
print(naturallog)
log10 = np.log10(arr1)
print(log10)

[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]
[0.         0.30103    0.47712125 0.60205999]


15. Create array: arr = [1.2, 2.5, 3.7, 4.1] Apply:

         round()
         floor()
         ceil() Explain differences based on output.

In [35]:
arr = np.array([1.2,2.5,3.7,4.1])

print(np.round(arr))
print(np.floor(arr))
print(np.ceil(arr))

[1. 2. 4. 4.]
[1. 2. 3. 4.]
[2. 3. 4. 5.]
