### Numpy_5 file 

np.unque to convert the array into set of unique elements


In [1]:
import numpy as np

In [2]:
arr = np.arange(1,11)

arr1 = np.unique(arr)
print(arr1)
print(type(arr1))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [3]:
arr2 = np.sort(arr1)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
##arg sort

arr0 = np.random.randint(1,100,10)
arr3 = np.argsort(arr0)
print(arr3)

[0 1 7 6 5 3 9 8 4 2]
