## Numpy Library - 13-05-2026
1. arrange - a = np.arange(1,101)
2. identity matrix- np.identity(3)
3. matrix filling , through random , Uniform distribution, Normal distribution - np.random.rand
4. need to learn this --->  rearrange , np.reshape, re size , differnece between reshape and resize, view and copy - difference between view and copy
**#ravel and flatten - difference between ravel and flatten, transpose - IMP interview Question**

In [2]:
import numpy as np

In [3]:
# arrange
a = np.arange(1,101)
print(a)


[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [4]:
#identity matri
from numpy import identity


np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#matrix filling , through random , Uniform distribution, Normal distribution , random intergers , random choice
np.random.seed(42) #this will lock the output

print(np.random.rand(3,3))
print(np.random.randn(3,3))
print(np.random.randint(1,100,(3,3)))
print(np.random.choice(['deep','desai','shallow',10,20],(3,3)))


[[0.12503181 0.55975449 0.82003465]
 [0.77333629 0.37046814 0.22815954]
 [0.01311013 0.76024629 0.47611554]]
[[ 1.66615013 -0.75420764  0.62994613]
 [-0.23608017 -0.51557357 -0.43607167]
 [-0.37795388  2.01479199  0.38148028]]
[[31 13 22]
 [92  7 68]
 [37  7 68]]
[['10' 'desai' 'deep']
 ['desai' 'desai' '20']
 ['deep' '20' 'desai']]


#need to learn this self---> 
# rearrange , np.reshape, re size , differnece between reshape and resize, view and copy - difference between view and copy
#ravel and flatten - difference between ravel and flatten, transpose 


In [9]:
arr = np.array(np.random.rand(10))
print(arr)

#1. reshape() — Change Shape Without Changing Data
new_arr = np.reshape(arr,(2,5))
print(new_arr)
print(arr)

[0.73683112 0.56785752 0.63211801 0.85731466 0.03038435 0.12447153
 0.08863285 0.08475624 0.68875312 0.6246692 ]
[[0.73683112 0.56785752 0.63211801 0.85731466 0.03038435]
 [0.12447153 0.08863285 0.08475624 0.68875312 0.6246692 ]]
[0.73683112 0.56785752 0.63211801 0.85731466 0.03038435 0.12447153
 0.08863285 0.08475624 0.68875312 0.6246692 ]


In [12]:
#resize() — Actually Modifies Original Array
arr= np.array(np.random.randn(15))
print(arr)
new_arr = np.resize(arr,(3,5))
print(new_arr)
arr.resize((3,5))
print(arr)

[-1.30432866  2.72201002 -0.38857489 -0.10611605 -1.30117791  0.89101628
 -1.35697025 -1.18503962 -1.22225098 -0.10316626  1.98113458 -0.58409232
 -0.48016031 -1.82664117  0.28043738]
[[-1.30432866  2.72201002 -0.38857489 -0.10611605 -1.30117791]
 [ 0.89101628 -1.35697025 -1.18503962 -1.22225098 -0.10316626]
 [ 1.98113458 -0.58409232 -0.48016031 -1.82664117  0.28043738]]
[[-1.30432866  2.72201002 -0.38857489 -0.10611605 -1.30117791]
 [ 0.89101628 -1.35697025 -1.18503962 -1.22225098 -0.10316626]
 [ 1.98113458 -0.58409232 -0.48016031 -1.82664117  0.28043738]]


### Difference: view() vs copy()
| Feature              | view() | copy()          |
| -------------------- | ------ | --------------- |
| Shares memory        | Yes    | No              |
| Faster               | Yes    | Slightly slower |
| Original changes too | Yes    | No              |


### ravel() — Flatten Array (Usually View)

In [31]:
arr = np.array(np.random.randint(0, 10, size=(5, 5)))
arr = arr.ravel()
print(arr)
arr = np.array(np.random.randint(0, 10, size=(5, 5)))
arr = arr.flatten()
print(arr)


[6 0 6 6 1 1 8 1 6 0 7 3 0 0 3 7 8 3 0 4 3 4 6 8 1]
[8 9 2 0 2 5 1 0 6 0 2 8 2 7 3 9 5 0 9 3 4 2 3 8 7]


In [ ]:

arr = np.array([[1,2],[3,4]])

print(arr.reshape(4))
print("------------------")

arr = np.array([[1,2],[3,4]])
arr1 = arr.ravel()
print(arr)

print(arr1)




print("------------------")


arr = np.array([[1,2],[3,4]])
arr1 = arr.flatten()
print(arr)
print(arr1)

print("------------------")

arr = np.array([[1,2],[3,4]])
print(arr.transpose())

[1 2 3 4]
------------------
[[1 2]
 [3 4]]
[1 2 3 4]
------------------
[[1 2]
 [3 4]]
[1 2 3 4]
------------------
[[1 3]
 [2 4]]
